sudo: false
language: ruby
rvm:
  - '1.8.7-p371'
  - '1.9.3-p551'
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.6'
  - '2.3.3'
  - '2.4.0'
  - 'jruby-1.7.26'
  - 'jruby-9.0.5.0'
  - 'jruby-9.1.5.0'
script:
  - make test
  - bundle exec image_optim --info
  - bundle exec rspec
before_install:
  if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install imagemagick; fi
matrix:
  fast_finish: true
  include:
    - os: osx
      rvm: default
    - env: RUBOCOP=✓
      rvm: '2'
      script: bundle exec rubocop
    - env: CHECK_RUBIES=✓
      rvm: '2'
      script: bundle exec travis_check_rubies
