sudo: false
language: ruby
rvm:
  - '1.8.7-p371'
  - '1.9.3-p551'
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.10'
  - '2.3.8'
  - '2.4.5'
  - '2.5.3'
  - 'jruby-9.0.5.0'
  - 'jruby-9.1.9.0'
script:
  - make test
  - bundle exec image_optim --info
  - bundle exec rspec
before_install:
  - gem install bundler
  - ruby -e 'require "rubygems"; require "bundler/inline"; gemfile{ source "https://rubygems.org"; gem "rubygems-update" }' # get compatible version of rubygems-update
  - gem update --system
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install imagemagick; fi
  - make ldd-version
matrix:
  include:
    - dist: trusty
      rvm: default
    - os: osx
      rvm: default
      osx_image: xcode7.3
    - os: osx
      rvm: default
      osx_image: xcode8.3
    - os: osx
      rvm: default
      osx_image: xcode9.3
    - env: RUBOCOP=✓
      rvm: '2.5.3'
      script: bundle exec rubocop
    - env: CHECK_RUBIES=✓
      rvm: '2.5.3'
      script: bundle exec travis_check_rubies
