language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-1.7.17-18mode
  - jruby-1.7.17-19mode
  - ree
script:
  if [ -z "$RUBOCOP" ]; then
    make test
    && bundle exec image_optim --info
    && bundle exec rspec
  ; else
    bundle exec rubocop
  ; fi
matrix:
  fast_finish: true
  include:
    - env: RUBOCOP=true
      rvm: default
